# Disclaimer: File was origonaly generated by Claude to quickly convert from previous config layout to new one.
# - Verified working and modified to its current state by xvr6

{ lib, ... }:
let
  # -- Use LF definitions; Rest of file is dedicated to converting it to eza
  rawLines = lib.splitString "\n" (builtins.readFile ../lf/icons);

  extSectionHeaders = [
    "# file extensions (vim-devicons)"
    "# Archives / Compressed"
    "# image formats: raster"
    "# image formats: vector / graphics"
    "# image formats: camera raw"
    "# video formats"
    "# audio formats"
    "# other formats"
  ];
  nameSectionHeaders = [
    "# file names (vim-devicons) (case-insensitive not supported in lf)"
    "# file names (case-sensitive adaptations)"
    "# file patterns (file name adaptations)"
  ];

  unquote =
    s:
    if lib.hasPrefix "'" s && lib.hasSuffix "'" s then
      lib.removeSuffix "'" (lib.removePrefix "'" s)
    else
      s;

  parseDataLine = builtins.match "^([^[:space:]]+)[[:space:]]+([^[:space:]#]+)[[:space:]]*(#.*)?$";

  step =
    acc: line:
    let
      trimmed = lib.trim line;
    in
    if trimmed == "" then
      acc
    else if lib.hasPrefix "#" trimmed then
      if builtins.elem trimmed extSectionHeaders then
        acc // { section = "ext"; }
      else if builtins.elem trimmed nameSectionHeaders then
        acc // { section = "name"; }
      else
        acc // { section = "skip"; } # type-code section / plain comments
    else
      let
        m = parseDataLine trimmed;
      in
      if m == null then
        acc
      else
        let
          pattern = unquote (builtins.elemAt m 0);
          icon = builtins.elemAt m 1;
        in
        if acc.section == "ext" && lib.hasPrefix "*." pattern then
          acc
          // {
            extensions = acc.extensions // {
              ${lib.removePrefix "*." pattern} = {
                icon = {
                  glyph = icon;
                };
              };
            };
          }
        else if acc.section == "name" then
          let
            name = if lib.hasPrefix "*" pattern then lib.removePrefix "*" pattern else pattern;
          in
          acc
          // {
            filenames = acc.filenames // {
              ${name} = {
                icon = {
                  glyph = icon;
                };
              };
            };
          }
        else
          acc;

  parsed = lib.foldl' step {
    section = "skip";
    extensions = { };
    filenames = { };
  } rawLines;
in
{
  programs.eza = {
    enable = true;
    icons = "auto";
    enableZshIntegration = false;
    theme = {
      extensions = parsed.extensions;
      filenames = parsed.filenames;
    };
  };
}
