[accessibility]
ui_scale = 1.25

[bar]
order = ["Right"]

[bar.Right]
capsule = true
center = ["media", "workspaces", "audio_visualizer"]
contact_shadow = true
end = ["group:g2", "group:g1", "session"]
position = "right"
radius = 28
scale = 1.25
start = ["control-center", "notifications", "output_volume", "active_window"]
thickness = 42

[[bar.Right.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g1"
members = ["clock", "-", "date"]
opacity = 1.0
padding = 6.0

[[bar.Right.capsule_group]]
accordion = false
accordion_direction = "start"
enabled = true
fill = "surface_variant"
id = "g2"
members = ["tray", "battery", "sysmon"]
opacity = 1.0
padding = 6.0

[battery.device."/org/freedesktop/UPower/devices/headset_dev_BC_3E_0B_21_04_D6"]
warning_threshold = 15

[calendar]

[control_center.calendar]
show_week_numbers = true

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = ["lockscreen-login-box@eDP-1"]

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 196.0
box_width = 810.0
cx = 1152.0
cy = 1244.800048828125
output = "eDP-1"
placement_height = 1536.0
placement_width = 2304.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[plugins]
enabled = ["aabidk20/yt-music"]

[shell]
settings_show_advanced = false

[shell.greeter_sync]
auto_sync = true

[shell.panel]
transparency_mode = "glass"

[theme]
mode = "dark"
shell_mode = "dark"
source = "wallpaper"
wallpaper_scheme = "dysfunctional"

[theme.templates]
builtin_ids = ["kitty", "umbriel"]
community_ids = ["claude-code", "zen-browser", "vscode", "obs", "yazi"]

[wallpaper.default]
path = "/home/xvr6/Pictures/Wallpapers/wallhaven_4xryxd.jpg"

[wallpaper.last]
path = "/home/xvr6/Pictures/Wallpapers/wallhaven_4xryxd.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/xvr6/Pictures/Wallpapers/wallhaven_4xryxd.jpg"

[widget.-]
length = 4
type = "spacer"

[widget.active_window]
show_empty_label = false

[widget.audio_visualizer]
bands = 92
capsule = true
capsule_padding = 4
capsule_radius = "auto"
color_2 = "secondary"
mirrored = false
scale = 0.90000000000000013
show_when_idle = true
width = 224

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
font_scale = 0.95
scale = 0.95

[widget.control-center]
custom_image_colorize = true

[widget.date]
format = "{:%a %b %d}"
scale = 0.85

[widget.media]
album_art_only = true

[widget.media.actions]
right = "exec noctalia msg panel-toggle aabidk20/yt-music:panel"

[widget.network]
scale = 1.35
show_label = false

[widget.output_volume]
show_label = false

[widget.sysmon]
show_value = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false
